#!/usr/bin/env python3
# D1/D2 — the storage entry must REFUSE an over-size diff, never truncate it.
#
# The entry used to be a bare `diff[:4000]` character slice applied AFTER the F2
# validation gate. Two things followed, and both are what these tests pin:
#
#   * it voided the gate's own contract ("never store a diff that fails git apply
#     --check") one statement after the gate enforced it;
#   * it reproduced the measured excerpt incident one layer down. That incident:
#     a 5331-char EDITABLE-merge diff was cut mid-word for the pre-verify prompt
#     and the verifier FAILed axis C3 on "truncated mid-sentence" — a verdict on
#     the fragment, not on the patch. The lesson is not "the diff is big", it is
#     "a partial diff is indistinguishable from a real one". A truncating storage
#     bound reproduces exactly that, so the disposition past the bound is refusal.
#
# The live instance was `classify_prose_only_add`, which reads the STORED diff: a
# subtraction patch whose removals sat past the 4000-char cut arrived at the
# detector as added-lines-only and was classified prose-only-add. Covered below:
#   (a) under the bound the diff is stored INTACT;
#   (b) past it the diff is REFUSED — not stored, named reason, loud stderr;
#   (c) the boundary is pinned from both sides (== stored, +1 refused);
#   (d) classification of a STORED diff is unchanged, and the refusal reaches
#       'reject' through the empty-diff arm that already existed;
#   (e) STORED_DIFF_CHAR_LIMIT <= DIFF_EXCERPT_CHAR_CAP, so _diff_excerpt returns
#       every stored diff byte-identical — the excerpt can no longer truncate one.
#
# Sizes are MEASURED through _parse_haiku_response itself rather than computed
# from the pipeline's internals: a fixture sized by arithmetic over strip() and
# header synthesis measures the test author's model of the code, not the code.
#
# Run: python3 -m unittest autoagent.test.test_stored_diff_bound
#   (or, from autoagent/test/) python3 -m unittest test_stored_diff_bound

from __future__ import annotations

import difflib
import functools
import io
import shutil
import subprocess
import sys
import tempfile
import unittest
from contextlib import redirect_stderr
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_HOOKS_DIR = _REPO_ROOT / "hooks"
_AUTOAGENT_DIR = _REPO_ROOT / "autoagent"

if str(_HOOKS_DIR) not in sys.path:
    sys.path.insert(0, str(_HOOKS_DIR))
if str(_AUTOAGENT_DIR) not in sys.path:
    sys.path.insert(0, str(_AUTOAGENT_DIR))

import daemon_cycle as dc  # noqa: E402 — autoagent dir prepended above

_AGENT_FILE = "glass-atrium-dev-db.md"
_OVERSIZE_MARKER = "OVERSIZE DIFF"

# A minimal agent body in the shape the loop actually edits. Small on purpose —
# the bound under test is on the DIFF, and a large fixture body would only make
# the sizing arithmetic below harder to read.
BEFORE_LINES = [
    "---\n",
    "name: glass-atrium-dev-db\n",
    "---\n",
    "\n",
    "## Work Rules\n",
    "<!-- EDITABLE:BEGIN -->\n",
    "- Schema changes -> migration files (no direct DDL)\n",
    "- Queries -> explicit SELECT fields (no SELECT *)\n",
    "<!-- EDITABLE:END -->\n",
]
BEFORE_BODY = "".join(BEFORE_LINES)


def _add_only_diff(name: str, added: list[str]) -> str:
    """A well-formed add-only unified diff appending `added` to the fixture body.

    Generated by difflib rather than hand-written so the @@ counts are correct by
    construction: a diff with wrong counts would take the F2 gate's REPAIR path
    and reach the storage entry at a length this fixture never chose.
    """
    after = BEFORE_LINES + added
    return "".join(
        difflib.unified_diff(
            BEFORE_LINES, after, fromfile=f"a/{name}", tofile=f"b/{name}"
        )
    )


def _filler(pad: int) -> str:
    """One appended bullet, padded to move the whole diff by exactly `pad` chars.

    Plain ASCII, and deliberately not shaped like a frontmatter identity line, so
    padding moves the SIZE and nothing else the classifiers key on. No space
    before the padding: at pad=0 that would leave the line ending in whitespace,
    which the parser's own strip() removes -- shifting the measured probe by a
    char and silently biasing every size derived from it.
    """
    return f"- retention note{'y' * pad}\n"


def _stdout(diff: str) -> str:
    """The Haiku response shape `_parse_haiku_response` parses."""
    return f"RATIONALE: bound the stored diff\nDIFF:\n{diff}"


def _capture(fn, *args, **kwargs) -> tuple[object, str]:
    """Run `fn`, returning (result, captured stderr)."""
    buf = io.StringIO()
    with redirect_stderr(buf):
        result = fn(*args, **kwargs)
    return result, buf.getvalue()


def _write_work_tree(name: str, body: str) -> tuple[Path, Path]:
    """Create a committed temporary git work tree holding one agent body.

    A real git repo because the gate resolves its apply scope through git — a
    bare temp dir would silently fall back to the operator's tree resolution.
    """
    work_tree = Path(tempfile.mkdtemp(prefix="d1-stored-diff-"))
    target = work_tree / name
    target.write_text(body, encoding="utf-8")
    subprocess.run(["git", "init", "-q", str(work_tree)], check=True)
    subprocess.run(["git", "-C", str(work_tree), "add", "-A"], check=True)
    subprocess.run(
        [
            "git", "-C", str(work_tree),
            "-c", "user.email=d1@test", "-c", "user.name=d1",
            "commit", "-qm", "fixture",
        ],
        check=True,
    )
    return work_tree, target


class _WorkTreeCase(unittest.TestCase):
    """Shared work tree — every test here is database-free and hermetic."""

    def setUp(self) -> None:
        self.work_tree, self.target = _write_work_tree(_AGENT_FILE, BEFORE_BODY)
        self.addCleanup(shutil.rmtree, self.work_tree, ignore_errors=True)
        # `_parse_haiku_response` reaches the gate indirectly and cannot pass the
        # agents-dir seam itself, so without this pin the apply scope resolves
        # against whatever install the operator happens to have — passing on a
        # developer box and failing on a clean runner. Torn down on test exit.
        unpinned = dc._gate_validated_diff
        dc._gate_validated_diff = functools.partial(  # type: ignore[assignment]
            unpinned, agents_dir=self.work_tree
        )
        self.addCleanup(setattr, dc, "_gate_validated_diff", unpinned)

    def parse(self, diff: str) -> tuple[dc.PatchProposal, str]:
        proposal, err = _capture(dc._parse_haiku_response, _stdout(diff), self.target)
        return proposal, err  # type: ignore[return-value]

    def diff_of_stored_size(self, want: int) -> str:
        """A diff the storage entry sees as exactly `want` chars.

        Measured, not derived: build one well under the bound, ask the parser what
        it actually stored, then pad the single filler line by the shortfall. The
        pad enters exactly one line, so the correction is exact — and it is
        re-measured and asserted below rather than assumed.
        """
        probe, _ = self.parse(_add_only_diff(self.target.name, [_filler(0)]))
        self.assertNotEqual(probe.proposed_diff, "", "probe must be stored intact")
        pad = want - len(probe.proposed_diff)
        self.assertGreaterEqual(pad, 0, "probe already exceeds the requested size")
        return _add_only_diff(self.target.name, [_filler(pad)])


class TestUnderBoundStoredIntact(_WorkTreeCase):
    """(a) Under the bound nothing changes — the diff is stored whole."""

    def test_when_diff_under_bound_then_stored_intact(self) -> None:
        diff = _add_only_diff(self.target.name, [_filler(0)])
        proposal, err = self.parse(diff)
        self.assertLess(len(diff), dc.STORED_DIFF_CHAR_LIMIT)
        # Byte-identical: the parser strips the DIFF section and the pipeline
        # restores the trailing newline, so nothing of the diff is lost.
        self.assertEqual(proposal.proposed_diff, diff)
        self.assertNotIn(_OVERSIZE_MARKER, err)
        self.assertFalse(
            proposal.rationale.startswith(dc.OVERSIZE_DIFF_REFUSAL_REASON_PREFIX)
        )

    def test_when_diff_at_incident_size_then_stored_intact(self) -> None:
        # 5331 chars — the historical EDITABLE-merge diff that overran the FORMER
        # 4000 bound. A fixed measurement, never read from the bound under test: a
        # fixture sized from that bound could only measure it against itself. It
        # must survive, or the refusal would reject exactly the legitimate release
        # content the excerpt incident was about.
        stored = self.parse(self.diff_of_stored_size(5331))[0].proposed_diff
        self.assertEqual(len(stored), 5331)


class TestPastBoundRefused(_WorkTreeCase):
    """(b) Past the bound the diff is refused — not stored, named, and loud."""

    def setUp(self) -> None:
        super().setUp()
        self.oversize = _add_only_diff(
            self.target.name, [_filler(dc.STORED_DIFF_CHAR_LIMIT)]
        )
        self.proposal, self.err = self.parse(self.oversize)

    def test_when_diff_past_bound_then_not_stored(self) -> None:
        self.assertGreater(len(self.oversize), dc.STORED_DIFF_CHAR_LIMIT)
        self.assertEqual(self.proposal.proposed_diff, "")

    def test_when_diff_past_bound_then_no_truncated_prefix_survives(self) -> None:
        # The distinguishing property: refusal, not a shorter diff. A truncating
        # bound would leave a prefix here that reads as a complete patch.
        self.assertNotIn("retention note", self.proposal.proposed_diff)

    def test_when_diff_past_bound_then_rationale_carries_named_reason(self) -> None:
        self.assertTrue(
            self.proposal.rationale.startswith(
                dc.OVERSIZE_DIFF_REFUSAL_REASON_PREFIX
            )
        )

    def test_when_diff_past_bound_then_refusal_is_loud(self) -> None:
        # Precondition Loud-Fail: the refusal is never silent.
        self.assertIn(_OVERSIZE_MARKER, self.err)
        self.assertIn(str(dc.STORED_DIFF_CHAR_LIMIT), self.err)

    def test_when_diff_past_bound_then_counts_survive_the_refusal(self) -> None:
        # The row still records the SIZE of what was refused; re-deriving from the
        # (now empty) stored diff would report zero.
        self.assertGreater(self.proposal.estimated_added_lines, 0)


class TestBoundaryPinnedBothSides(_WorkTreeCase):
    """(c) Exactly at the bound is stored; one char past it is refused."""

    def test_when_diff_exactly_at_bound_then_stored(self) -> None:
        at_bound = self.diff_of_stored_size(dc.STORED_DIFF_CHAR_LIMIT)
        proposal, err = self.parse(at_bound)
        self.assertEqual(len(proposal.proposed_diff), dc.STORED_DIFF_CHAR_LIMIT)
        self.assertNotIn(_OVERSIZE_MARKER, err)

    def test_when_diff_one_char_past_bound_then_refused(self) -> None:
        over = self.diff_of_stored_size(dc.STORED_DIFF_CHAR_LIMIT + 1)
        proposal, err = self.parse(over)
        self.assertEqual(proposal.proposed_diff, "")
        # Pins the comparison from the implementation's OWN view of the length,
        # which a stored-side assertion cannot reach once the diff is refused.
        self.assertIn(
            f"{_OVERSIZE_MARKER}: {dc.STORED_DIFF_CHAR_LIMIT + 1} chars", err
        )


class TestClassificationUnchanged(_WorkTreeCase):
    """(d) The reject path does not change how a STORED diff is classified."""

    def test_when_stored_then_patch_area_verdict_unchanged(self) -> None:
        proposal, _ = self.parse(_add_only_diff(self.target.name, [_filler(0)]))
        self.assertEqual(
            dc.classify_patch_area(
                proposal, self.target, agents_dir=self.work_tree
            ),
            "body-auto",
        )

    def test_when_refused_then_reject_via_the_existing_empty_diff_arm(self) -> None:
        proposal, _ = self.parse(
            _add_only_diff(self.target.name, [_filler(dc.STORED_DIFF_CHAR_LIMIT)])
        )
        self.assertEqual(
            dc.classify_patch_area(
                proposal, self.target, agents_dir=self.work_tree
            ),
            "reject",
        )
        # Reached through R3 (empty diff), the arm that already existed — not a
        # new branch. Pinned by showing an empty-diff proposal built any other way
        # reaches the same verdict.
        self.assertEqual(proposal.proposed_diff, "")

    def test_when_stored_then_prose_only_add_verdict_unchanged(self) -> None:
        proposal, _ = self.parse(_add_only_diff(self.target.name, [_filler(0)]))
        verdict = dc.classify_prose_only_add(
            proposal.proposed_diff, target_file=str(self.target)
        )
        self.assertEqual(verdict["classification"], "prose-only-add")
        self.assertTrue(verdict["warning"])
        self.assertEqual(verdict["removed_lines"], 0)

    def test_when_refused_then_verdict_is_unclassified_not_a_false_negative(
        self,
    ) -> None:
        # The call site guards on `if proposal.proposed_diff:`, so a refused row
        # classifies NOTHING and writes no key — absent reads as UNCLASSIFIED,
        # which is the whole point: a truncated diff would have been classified,
        # and classified WRONG (removals past the cut read as prose-only-add).
        proposal, _ = self.parse(
            _add_only_diff(self.target.name, [_filler(dc.STORED_DIFF_CHAR_LIMIT)])
        )
        self.assertFalse(proposal.proposed_diff)
        self.assertNotIn(
            dc.PROSE_ONLY_ADD_AXIS_KEY, dc._compose_pre_verify_axes(None, None)
        )


class TestExcerptCannotTruncateAStoredDiff(unittest.TestCase):
    """(e) The bound's relation to the excerpt cap, and what it buys."""

    def test_stored_bound_does_not_exceed_the_excerpt_cap(self) -> None:
        self.assertLessEqual(
            dc.STORED_DIFF_CHAR_LIMIT, dc.DIFF_EXCERPT_CHAR_CAP
        )

    def test_when_diff_is_at_the_stored_bound_then_excerpt_is_byte_identical(
        self,
    ) -> None:
        # The consequence of the relation above: the pre-verify verifier can no
        # longer be handed a fragment of a stored diff, whatever its size.
        largest = "+x\n" * (dc.STORED_DIFF_CHAR_LIMIT // 3)
        self.assertLessEqual(len(largest), dc.STORED_DIFF_CHAR_LIMIT)
        excerpt, err = _capture(
            dc._diff_excerpt, largest, dc.DIFF_EXCERPT_CHAR_CAP
        )
        self.assertEqual(excerpt, largest)
        self.assertNotIn(dc.DIFF_EXCERPT_MARKER_PREFIX, str(excerpt))
        self.assertEqual(err, "")


if __name__ == "__main__":
    unittest.main()
